https://github.com/eurogiro/innersource/blob/main/_config.ymltheme: jekyll-theme-cayman
title: InnerSource Toolkit
description: Best practices and templates for adopting InnerSource practices.
show_downloads: true

- name: Azure WebApp
  uses: Azure/webapps-deploy@v2
